# Generated by Django 6.0.5 on 2026-05-23 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni_cuit', models.CharField(blank=True, max_length=13, verbose_name='DNI / CUIT')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Inquilino',
                'verbose_name_plural': 'Inquilinos',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('padron_catastral', models.CharField(blank=True, max_length=50, verbose_name='Padrón Catastral')),
                ('padron_municipal', models.CharField(blank=True, max_length=50, verbose_name='Padrón Municipal')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('alquilada', 'Alquilada'), ('mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['domicilio'],
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cuit', models.CharField(blank=True, max_length=13)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ServicioImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('servicio', 'Servicio'), ('impuesto', 'Impuesto')], max_length=20)),
                ('icono', models.CharField(blank=True, help_text='Clase de ícono FontAwesome', max_length=50)),
            ],
            options={
                'verbose_name': 'Servicio / Impuesto',
                'verbose_name_plural': 'Servicios e Impuestos',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('operador', 'Operador'), ('consulta', 'Consulta')], default='consulta', max_length=20)),
                ('telefono_whatsapp', models.CharField(blank=True, max_length=20)),
                ('notif_email', models.BooleanField(default=True)),
                ('notif_whatsapp', models.BooleanField(default=False)),
                ('dias_anticipacion', models.PositiveIntegerField(default=7)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('escritura', 'Escritura'), ('plano', 'Plano'), ('seguro', 'Póliza de Seguro'), ('contrato', 'Contrato'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('url_drive', models.URLField(blank=True)),
                ('archivo', models.FileField(blank=True, upload_to='documentos/')),
                ('notas', models.TextField(blank=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.propiedad')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('monto_alquiler', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos Argentinos'), ('USD', 'Dólares')], default='ARS', max_length=3)),
                ('ajuste_meses', models.PositiveIntegerField(default=3, verbose_name='Ajuste cada (meses)')),
                ('porcentaje_ajuste', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('vencido', 'Vencido'), ('rescindido', 'Rescindido')], default='activo', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.inquilino')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.propiedad')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='propiedad',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propiedades', to='core.propietario'),
        ),
        migrations.CreateModel(
            name='PropiedadServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(blank=True, max_length=100, verbose_name='N° de Cuenta / Servicio')),
                ('numero_medidor', models.CharField(blank=True, max_length=100, verbose_name='N° de Medidor')),
                ('responsable_pago', models.CharField(choices=[('propietario', 'Propietario'), ('inquilino', 'Inquilino')], default='propietario', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='core.propiedad')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.servicioimpuesto')),
            ],
            options={
                'verbose_name': 'Servicio de Propiedad',
                'verbose_name_plural': 'Servicios de Propiedades',
                'unique_together': {('propiedad', 'servicio')},
            },
        ),
        migrations.CreateModel(
            name='TitularPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('es_titular_principal', models.BooleanField(default=False)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.propiedad')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.propietario')),
            ],
            options={
                'verbose_name': 'Titular de Propiedad',
                'verbose_name_plural': 'Titulares de Propiedades',
                'unique_together': {('propiedad', 'titular')},
            },
        ),
        migrations.AddField(
            model_name='propiedad',
            name='titulares',
            field=models.ManyToManyField(related_name='propiedades_como_titular', through='core.TitularPropiedad', to='core.propietario'),
        ),
        migrations.CreateModel(
            name='Vencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField()),
                ('importe_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('periodo', models.CharField(blank=True, help_text='Ej: Enero 2025', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('propiedad_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vencimientos', to='core.propiedadservicio')),
            ],
            options={
                'verbose_name': 'Vencimiento',
                'verbose_name_plural': 'Vencimientos',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('importe_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_comprobante', models.CharField(blank=True, max_length=100, verbose_name='N° Comprobante')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vencimiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='core.vencimiento')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
