# Generated by Django 6.0.6 on 2026-06-10 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('titular', models.CharField(choices=[('drogueria_san_juan', 'Droguería San Juan SRL'), ('noroeste_nutricion', 'Noroeste Nutrición SRL'), ('socio', 'Socio'), ('otro', 'Otro')], max_length=30)),
                ('titular_nombre', models.CharField(blank=True, help_text="Si el titular es 'Otro', especificar nombre", max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['patente'],
            },
        ),
        migrations.CreateModel(
            name='SeguroVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compania', models.CharField(max_length=100, verbose_name='Compañía aseguradora')),
                ('numero_poliza', models.CharField(max_length=50, verbose_name='N° de póliza')),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguros', to='core.vehiculo')),
            ],
            options={
                'verbose_name': 'Seguro de Vehículo',
                'verbose_name_plural': 'Seguros de Vehículos',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='PatenteVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Ej: Enero 2025', max_length=20)),
                ('fecha_vencimiento', models.DateField()),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('importe_pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('numero_comprobante', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patentes', to='core.vehiculo')),
            ],
            options={
                'verbose_name': 'Patente de Vehículo',
                'verbose_name_plural': 'Patentes de Vehículos',
                'ordering': ['fecha_vencimiento'],
            },
        ),
    ]
