from django.contrib import admin
from django.urls import path
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('', views.dashboard, name='dashboard'),
    path('propietarios/', views.propietarios_lista, name='propietarios_lista'),
    path('propietarios/nuevo/', views.propietario_crear, name='propietario_crear'),
    path('propietarios/<int:pk>/editar/', views.propietario_editar, name='propietario_editar'),
    path('propiedades/', views.propiedades_lista, name='propiedades_lista'),
    path('propiedades/nueva/', views.propiedad_crear, name='propiedad_crear'),
    path('propiedades/<int:pk>/', views.propiedad_detalle, name='propiedad_detalle'),
    path('propiedades/<int:pk>/editar/', views.propiedad_editar, name='propiedad_editar'),
    path('propiedades/<int:pk>/eliminar/', views.propiedad_eliminar, name='propiedad_eliminar'),
    path('propiedades/<int:propiedad_pk>/servicio/', views.servicio_agregar, name='servicio_agregar'),
    path('propiedades/<int:propiedad_pk>/titular/', views.titular_agregar, name='titular_agregar'),
    path('propiedades/<int:propiedad_pk>/vencimiento/', views.vencimiento_crear, name='vencimiento_crear_propiedad'),
    path('propiedades/<int:propiedad_pk>/contrato/', views.contrato_crear, name='contrato_crear_propiedad'),
    path('vencimientos/', views.vencimientos_lista, name='vencimientos_lista'),
    path('vencimientos/nuevo/', views.vencimiento_crear, name='vencimiento_crear'),
    path('vencimientos/<int:pk>/editar/', views.vencimiento_editar, name='vencimiento_editar'),
    path('vencimientos/<int:pk>/eliminar/', views.vencimiento_eliminar, name='vencimiento_eliminar'),
    path('vencimientos/<int:vencimiento_id>/pagar/', views.registrar_pago, name='registrar_pago'),
    path('servicios/', views.servicios_lista, name='servicios_lista'),
    path('servicios/nuevo/', views.servicio_crear, name='servicio_crear'),
    path('servicios/<int:pk>/editar/', views.servicio_editar, name='servicio_editar'),
    path('servicios/<int:pk>/eliminar/', views.servicio_eliminar, name='servicio_eliminar'),
    path('inquilinos/', views.inquilinos_lista, name='inquilinos_lista'),
    path('inquilinos/nuevo/', views.inquilino_crear, name='inquilino_crear'),
    path('inquilinos/<int:pk>/editar/', views.inquilino_editar, name='inquilino_editar'),
    path('inquilinos/<int:pk>/eliminar/', views.inquilino_eliminar, name='inquilino_eliminar'),
    path('contratos/', views.contratos_lista, name='contratos_lista'),
    path('contratos/nuevo/', views.contrato_crear, name='contrato_crear'),
    path('contratos/<int:pk>/editar/', views.contrato_editar, name='contrato_editar'),
    path('contratos/<int:pk>/eliminar/', views.contrato_eliminar, name='contrato_eliminar'),
    path('alertas/enviar/', views.enviar_alertas_view, name='enviar_alertas'),
    path('exportar/', views.exportar_excel, name='exportar_excel'),
    path('pagos/', views.pagos_lista, name='pagos_lista'),
    path('usuarios/', views.usuarios_lista, name='usuarios_lista'),
    path('usuarios/nuevo/', views.usuario_crear, name='usuario_crear'),
    path('usuarios/<int:pk>/editar/', views.usuario_editar, name='usuario_editar'),
    path('usuarios/<int:pk>/eliminar/', views.usuario_eliminar, name='usuario_eliminar'),
]
